apiVersion : apps/v1
kind: Deployment
metadata:
  name: dstincentives 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dstincentives
  template:
    metadata:
      labels:
        app: dstincentives 
    spec:
      containers:
        - name: dstincentives 
          image: containerregistry4pd7i.azurecr.io/dstincentives
          ports:
          - containerPort: 80